### ISSUE TITLE
unrecognized argument --max-lr

### ISSUE THREAD

**Issue by cifkao** [ofirpress/attention_with_linear_biases#2]
I tried to run the training command from the readme, but I get the following error:
```
train.py: error: unrecognized arguments: --max-lr 1.0 
```

**Comment by ofirpress** [comment]
I'm very sorry about that, thanks for pointing this out! I've updated the README and training should now work. Please respond here if it doesn't.

**Comment by cifkao** [comment]
Thanks for the fix!

Just one thing: the text says 512 tokens but the new command says `--tokens-per-sample 1024`. If I want to use 512, can I keep the other settings as they are?

**Comment by ofirpress** [comment]
Yup that was a mistake, fixed that now too. Thanks!
