### ISSUE TITLE
ALiBi during inference

### ISSUE THREAD

**Issue by VarunGumma** [ofirpress/attention_with_linear_biases#20]
Hi @ofirpress , I have been using your implementation of alibi, and I had the following question:

In the `transformer_decoder`, I see that the alibi bias is being added to the causal attention mask and used. But during inference, the `attn_mask` is `None`, which means no bias is added during the validation/testing which is not correct. Can you please give me more information about it?

**Comment by ofirpress** [comment]
Hi I haven't read this code in 2-3 years. ALiBi masks should be applied both at training and validation/testing. Maybe check out https://huggingface.co/mosaicml/mpt-7b-storywriter for a more modern working implementation of ALiBi.
